/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-111062-g09621fd7d9-20230612"
#endif /* AVUTIL_FFVERSION_H */
